import React, {FunctionComponent, PropsWithChildren} from 'react'
import {Metadata} from 'next'
import {TheHeader} from '@/components/theHeader/TheHeader'
import {TheFooter} from '@/components/theFooter/TheFooter'

import styles from '../../app/styles/Layout.module.scss'

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app'
}

interface Props extends PropsWithChildren {
    isFooterHidden?: boolean;
    isHeaderHidden?: boolean
}

const Layout: FunctionComponent<Props> = ({children, isFooterHidden = false, isHeaderHidden = false}) => {
    return (
        <div className={styles.wrapperContent}>
            {!isHeaderHidden && (
                <div className={styles.header}>
                    <TheHeader/>
                </div>
            )}
            <main className={styles.conteiner}>{children}</main>

            {!isFooterHidden && (
                <div className={styles.footer}>
                    <TheFooter/>
                </div>
            )}
        </div>
    )
}


export default Layout